### ISSUE TITLE
[BUG] Empty environment causes GUI to break

### ISSUE THREAD

**Issue by RicardoMusch** [cpenv/tk-cpenv#22]
When an empty environment for the engine to be loaded exists in the current project the choice menu breaks.

**Steps to reproduce:**

1. Make two environments for a software, example `Nuke` and `Nuketest` - tk-nuke
2. Add modules to `Nuke` but none to `Nuketest`
3. Launch Nuke
4. The Popup UI will break with the following error:

``` python
Traceback (most recent call last):
  File "C:\Users\ricardom\AppData\Roaming\somepath\p815c2015.basic.desktop\cfg\install\core\python\tank\platform\engine.py", line 1686, in _create_widget
    widget = derived_widget_class(*args, **kwargs)
  File "S:\_cache\shotgrid\bundle_cache\github\cpenv\tk-cpenv\v0.5.10\python\cpenv_ui\env_selector.py", line 42, in __init__
    + '\n'.join(environment['sg_requires'].split())
AttributeError: 'NoneType' object has no attribute 'split'
```
![image](https://user-images.githubusercontent.com/54025297/186730667-a7a1c531-003c-48b2-af40-b7337f5125de.png)

**Comment by danbradham** [comment]
Thanks for reporting @RicardoMusch.
