### ISSUE TITLE
software_entity can be None in before_app_launch

### ISSUE THREAD

**Issue by danbradham** [cpenv/tk-cpenv#7]
In some setups, maybe with shotgun configs that do not use the newer software discovery mechanism for Shotgun, software_entity was None in before_app_launch.

```
2020-08-07 12:01:21,109 [   ERROR] [PROXY] Failed to activate cpenv modules.
Traceback (most recent call last):
  File "...\tk-multi-launchapp\before_app_launch.py", line 68, in execute
    **kwargs
  File ".../_bundle_cache\github\cpenv\tk-cpenv\v0.3.2\app.py", line 171, in before_app_launch
    engine = software_entity.get('engine', engine_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by danbradham** [comment]
Fixed in v0.3.3
